Repository kittinunf/fuel, pull requests merged in 2018-10, with the labels that each got.

#452 Fix a typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: :book: documentation

#424 Integration with Project Reactor
  README.md
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  fuel-reactor/build.gradle.kts
  fuel-reactor/src/main/kotlin/com/github/kittinunf/fuel/reactor/Reactor.kt
  fuel-reactor/src/test/kotlin/com/github/kittinunf/fuel/reactor/MockHelper.kt
  fuel-reactor/src/test/kotlin/com/github/kittinunf/fuel/reactor/ReactorTest.kt
  settings.gradle.kts
Labels: :gem: feature

#450 add kotlinxSerialization JSON deseriallization
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  fuel-kotlinx-serialization/build.gradle.kts
  fuel-kotlinx-serialization/src/main/kotlin/com/github/kittinunf/fuel/serialization/FuelSerialization.kt
  fuel-kotlinx-serialization/src/test/kotlin/com/github/kittinunf/fuel/FuelKotlinxSerializationTest.kt
  fuel-kotlinx-serialization/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  settings.gradle.kts
Labels: :gem: feature

#459 Fix publishing script
  deploy_bintray.sh
Labels: :notebook: chore

#460 Fix minor details on PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :notebook: chore

#438 Add suspending implenetation client
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  fuel-coroutines/build.gradle.kts
  fuel-coroutines/src/main/kotlin/com/github/kittinunf/fuel/coroutines/Coroutines.kt
  fuel-coroutines/src/test/kotlin/com/github/kittinunf/fuel/coroutines/CoroutinesTest.kt
  fuel-kotlinx-serialization/build.gradle.kts
  fuel/src/main/kotlin/com/github/kittinunf/fuel/Fuel.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Client.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Deserializable.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/RedirectionInterceptor.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/SuspendingRequest.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/CustomClientTest.kt
  gradle/wrapper/gradle-wrapper.properties
  sample/build.gradle.kts
  sample/src/main/kotlin/com/example/fuel/MainActivity.kt
  settings.gradle.kts
Labels: :bug: bug, Kotlin 1.3

#462 [Release] New Version 1.16.0
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  gradle/wrapper/gradle-wrapper.jar
Labels: :notebook: chore

#465 Replace buildscript with plugin DSL
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  fuel-kotlinx-serialization/build.gradle.kts
  settings.gradle.kts
Labels: :notebook: chore

#471 Unify constants
  build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/Versions.kt
  fuel-android/build.gradle.kts
  fuel-coroutines/build.gradle.kts
  fuel-forge/build.gradle.kts
  fuel-gson/build.gradle.kts
  fuel-jackson/build.gradle.kts
  fuel-kotlinx-serialization/build.gradle.kts
  fuel-livedata/build.gradle.kts
  fuel-moshi/build.gradle.kts
  fuel-reactor/build.gradle.kts
  fuel-rxjava/build.gradle.kts
  fuel/build.gradle.kts
  sample-java/build.gradle.kts
  sample/build.gradle.kts
  settings.gradle.kts
Labels: :notebook: chore

#454 Improve Gson Coverages
  fuel-gson/src/main/kotlin/com/github/kittinunf/fuel/gson/FuelGson.kt
  fuel-gson/src/test/kotlin/com/github/kittinunf/fuel/FuelGsonTest.kt
Labels: :boom: breaking change, :notebook: chore, :unicorn: enhancement

#477 Add reviewdog to bark at our violations
  .travis.yml
  add_review.sh
  build.gradle.kts
  fuel-android/src/main/kotlin/com/github/kittinunf/fuel/android/core/Json.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/BaseTestCase.kt
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: :notebook: chore, :unicorn: enhancement

#483 Bump min SDk (Android) and JRE (Java)
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
Labels: :boom: breaking change, :notebook: chore

#481 Header normalisation and request fixes
  README.md
  buildSrc/src/main/kotlin/Constants.kt
  fuel-coroutines/build.gradle.kts
  fuel-moshi/build.gradle.kts
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Encoding.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Headers.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Method.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Response.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/RedirectionInterceptor.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/SuspendingRequest.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/TaskRequest.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/UploadTaskRequest.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/util/FuelRouting.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/BlockingRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHeaderTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHeadersTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestUploadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RoutingTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/HeadersTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/ResponseTest.kt
  sample/build.gradle.kts
  sample/src/androidTest/kotlin/com/example.fuel/MainActivityTest.kt
  sample/src/main/kotlin/com/example/fuel/MainActivity.kt
Labels: :boom: breaking change, :bug: bug, :unicorn: enhancement

#487 Update kotlin and libraries to 1.3.0
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  fuel-kotlinx-serialization/build.gradle.kts
  fuel-kotlinx-serialization/src/main/kotlin/com/github/kittinunf/fuel/serialization/FuelSerialization.kt
  fuel-kotlinx-serialization/src/test/kotlin/com/github/kittinunf/fuel/FuelKotlinxSerializationTest.kt
  settings.gradle.kts
Labels: :boom: breaking change, Kotlin 1.3
