Repository kittinunf/fuel, pull requests merged in 2018-12, with the labels that each got.

#553 Parameter encoding for all requests
  fuel/README.md
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/BodyRepresentation.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Encoding.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/RequestExecutionOptions.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/LoggingInterceptors.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/ParameterEncoder.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/EncodingTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/ReadmeIntegrityTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/interceptors/ParameterEncoderTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/interceptors/RedirectionInterceptorTest.kt
Labels: :unicorn: enhancement

#558 Add download to stream functionality
  fuel/README.md
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DownloadRequest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestPathStringConvertibleExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestSharedInstanceTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestStringExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/ResponseProgressTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/requests/CancellableRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/requests/DownloadRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/issues/RedirectProgressIssue416.kt
Labels: :gem: feature

#559 Overhaul upload requests, Blob and DataPart
  fuel-coroutines/src/test/kotlin/com/github/kittinunf/fuel/coroutines/StringTest.kt
  fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/issues/ResponseLoggingIssue364.kt
  fuel-test/src/main/kotlin/com/github/kittinunf/fuel/test/MockHelper.kt
  fuel/README.md
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Blob.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/DataPart.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/UploadBody.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/UploadRequest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/BlockingRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestPathStringConvertibleExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestProgressTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestSharedInstanceTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestStringExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/interceptors/ParameterEncoderTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/requests/UploadRequestTest.kt
  sample/src/main/kotlin/com/example/fuel/MainActivity.kt
Labels: :boom: breaking change, :gem: feature, :unicorn: enhancement

#561 Migrate to Android API Level 28 and AndroidX
  .travis.yml
  buildSrc/src/main/kotlin/Constants.kt
  fuel-livedata/build.gradle.kts
  fuel-livedata/src/main/kotlin/com/github/kittinunf/fuel/livedata/FuelLiveData.kt
  fuel-livedata/src/test/kotlin/com/github/kittinunf/fuel/livedata/FuelLiveDataTest.kt
  sample/build.gradle.kts
  sample/src/main/kotlin/com/example/fuel/MainActivity.kt
Labels: :boom: breaking change
