Repository kittinunf/fuel, pull requests merged in 2018-09, with the labels that each got.

#432 Add missing HTTP methods
  README.md
  fuel/src/main/kotlin/com/github/kittinunf/fuel/Fuel.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Method.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestTest.kt
Labels: feature

#434 Testing: mock all the things
  .gitignore
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  fuel/build.gradle.kts
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Response.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/BlockingRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/HttpHeadRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/MockHttpTestCase.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestAuthenticationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestDownloadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHandlerTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHeaderTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestObjectTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestPathStringConvertibleExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestSharedInstanceTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestStringExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestUploadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestValidationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RoutingTest.kt
Labels: enhancement, feature

#435 Much Better Base64 Implemenation
  fuel/src/main/java/com/github/kittinunf/fuel/util/Base64.java
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/util/Base64.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestAuthenticationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RoutingTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/util/Base64Test.java
  fuel/src/test/kotlin/com/github/kittinunf/fuel/util/Base64Test.kt
Labels: enhancement

#444 Mock all the projects
  fuel-android/build.gradle.kts
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/BaseTestCase.kt
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/MockHelper.kt
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidSyncTest.kt
  fuel-coroutines/build.gradle.kts
  fuel-coroutines/src/test/kotlin/com/github/kittinunf/fuel/coroutines/CoroutinesTest.kt
  fuel-coroutines/src/test/kotlin/com/github/kittinunf/fuel/coroutines/MockHelper.kt
  fuel-forge/build.gradle.kts
  fuel-forge/src/test/kotlin/com/github/kittinunf/fuel/forge/FuelForgeTest.kt
  fuel-forge/src/test/kotlin/com/github/kittinunf/fuel/forge/MockHelper.kt
  fuel-gson/build.gradle.kts
  fuel-gson/src/test/kotlin/com/github/kittinunf/fuel/FuelGsonTest.kt
  fuel-gson/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-jackson/build.gradle.kts
  fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/FuelJacksonTest.kt
  fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-livedata/build.gradle.kts
  fuel-livedata/src/test/kotlin/com/github/kittinunf/fuel/livedata/FuelLiveDataTest.kt
  fuel-livedata/src/test/kotlin/com/github/kittinunf/fuel/livedata/MockHelper.kt
  fuel-moshi/build.gradle.kts
  fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt
  fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-rxjava/build.gradle.kts
  fuel-rxjava/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-rxjava/src/test/kotlin/com/github/kittinunf/fuel/RxFuelTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/BlockingRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/CustomClientTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/MockHttpTestCase.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestAuthenticationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestDownloadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHandlerTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHeaderTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestObjectTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestPathStringConvertibleExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestSharedInstanceTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestStringExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestUploadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestValidationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RoutingTest.kt
Labels: :unicorn: enhancement

#443 Fixed and Improve Coverage of Forge
  fuel-forge/src/main/java/com/github/kittinunf/fuel/forge/FuelForge.kt
Labels: :bug: bug
