Repository kittinunf/fuel, pull requests merged in 2018-11, with the labels that each got.

#490 Change Rx extension names
  fuel-rxjava/src/main/kotlin/com/github/kittinunf/fuel/rx/RxFuel.kt
  fuel-rxjava/src/test/kotlin/com/github/kittinunf/fuel/RxFuelTest.kt
  sample/src/main/kotlin/com/example/fuel/MainActivity.kt
Labels: :unicorn: enhancement

#496 support chunked content encoding
  fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt
Labels: :bug: bug

#491 Generic progress reporting
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Body.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Progress.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/RedirectionInterceptor.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DownloadTaskRequest.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/UploadTaskRequest.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/util/InputStreams.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/util/ProgressInputStream.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/util/ProgressOutputStream.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/EncodingTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/MockHttpTestCase.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestDownloadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestProgressTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/ResponseProgressTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/issues/RedirectProgressIssue416.kt
Labels: :gem: feature

#499 Remove Content-Length if there is Transfer-Encoding
  fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/toolbox/TransferEncodingTest.kt
Labels: :bug: bug

#503 Separate shared test project for mocking and more
  fuel-android/build.gradle.kts
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/BaseTestCase.kt
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/MockHelper.kt
  fuel-coroutines/build.gradle.kts
  fuel-coroutines/src/test/kotlin/com/github/kittinunf/fuel/coroutines/CoroutinesTest.kt
  fuel-coroutines/src/test/kotlin/com/github/kittinunf/fuel/coroutines/MockHelper.kt
  fuel-forge/build.gradle.kts
  fuel-forge/src/test/kotlin/com/github/kittinunf/fuel/forge/FuelForgeTest.kt
  fuel-forge/src/test/kotlin/com/github/kittinunf/fuel/forge/MockHelper.kt
  fuel-gson/build.gradle.kts
  fuel-gson/src/test/kotlin/com/github/kittinunf/fuel/FuelGsonTest.kt
  fuel-gson/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-jackson/build.gradle.kts
  fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/FuelJacksonTest.kt
  fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/issues/ResponseLoggingIssue364.kt
  fuel-kotlinx-serialization/build.gradle.kts
  fuel-kotlinx-serialization/src/test/kotlin/com/github/kittinunf/fuel/FuelKotlinxSerializationTest.kt
  fuel-kotlinx-serialization/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-livedata/build.gradle.kts
  fuel-livedata/src/test/kotlin/com/github/kittinunf/fuel/livedata/FuelLiveDataTest.kt
  fuel-livedata/src/test/kotlin/com/github/kittinunf/fuel/livedata/MockHelper.kt
  fuel-moshi/build.gradle.kts
  fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt
  fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-reactor/build.gradle.kts
  fuel-reactor/src/test/kotlin/com/github/kittinunf/fuel/reactor/MockHelper.kt
  fuel-reactor/src/test/kotlin/com/github/kittinunf/fuel/reactor/ReactorTest.kt
  fuel-rxjava/build.gradle.kts
  fuel-rxjava/src/test/kotlin/com/github/kittinunf/fuel/MockHelper.kt
  fuel-rxjava/src/test/kotlin/com/github/kittinunf/fuel/RxFuelTest.kt
  fuel-test/build.gradle.kts
  fuel-test/src/main/kotlin/com/github/kittinunf/fuel/test/MockHelper.kt
  fuel-test/src/main/kotlin/com/github/kittinunf/fuel/test/MockHttpTestCase.kt
  fuel/build.gradle.kts
  fuel/src/test/kotlin/com/github/kittinunf/fuel/BlockingRequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/MockHttpTestCase.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestAuthenticationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestDownloadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHandlerTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestObjectTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestPathStringConvertibleExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestProgressTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestSharedInstanceTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestStringExtensionTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestUploadTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestValidationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/ResponseProgressTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RoutingTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/issues/BodyInterceptorIssue464.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/issues/ContentTypeHeaderIssue408.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/issues/ContentTypeHeaderIssue473.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/issues/DeleteIssue306.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/issues/RedirectProgressIssue416.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/toolbox/ContentEncodingTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/toolbox/HttpClientTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/toolbox/TransferEncodingTest.kt
  settings.gradle.kts
Labels: :notebook: chore

#521 Migrate publishing plugin
  build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  deploy_bintray.sh
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: :notebook: chore, :unicorn: enhancement

#534 Documentation for 2.0.0
  README.legacy.md
  README.md
  fuel-android/README.md
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidSyncTest.kt
  fuel-coroutines/README.md
  fuel-forge/README.md
  fuel-gson/README.md
  fuel-jackson/README.md
  fuel-kotlinx-serialization/README.md
  fuel-livedata/README.md
  fuel-moshi/README.md
  fuel-reactor/README.md
  fuel-rxjava/README.md
  fuel-test/README.md
  fuel/README.md
  fuel/src/main/kotlin/com/github/kittinunf/fuel/Fuel.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/ReadmeIntegrityTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestStringExtensionTest.kt
Labels: :book: documentation

#540 Update Result version
  buildSrc/src/main/kotlin/Constants.kt
Labels: :gem: feature

#533 Move JSONObject into a new Module
  fuel-android/build.gradle.kts
  fuel-android/src/main/kotlin/com/github/kittinunf/fuel/android/core/Json.kt
  fuel-android/src/main/kotlin/com/github/kittinunf/fuel/android/extension/Requests.kt
  fuel-android/src/test/kotlin/com/github/kittinunf/fuel/android/RequestAndroidAsyncTest.kt
  fuel-json/build.gradle.kts
  fuel-json/src/main/kotlin/com/github/kittinunf/json/FuelJson.kt
  fuel-json/src/test/kotlin/com/github/kittinunf/json/FuelJsonTest.kt
  settings.gradle.kts
Labels: :boom: breaking change

#542 Add option to use .editorConfig in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: :book: documentation

#551 Reset Fuel Manager on Two Tests
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestHandlerTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestSharedInstanceTest.kt
Labels: :bug: bug
