Repository kittinunf/fuel, pull requests merged in 2019-01, with the labels that each got.

#574 Add jitpack to instructions
  README.md
Labels: :book: documentation

#571 [fuel-core] Integate Stetho
  build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  fuel-stetho/.gitignore
  fuel-stetho/build.gradle.kts
  fuel-stetho/proguard-rules.pro
  fuel-stetho/src/main/AndroidManifest.xml
  fuel-stetho/src/main/java/com/kittinunf/fuel/stetho/StethoHook.kt
  fuel-stetho/src/main/res/values/strings.xml
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Client.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/DefaultHook.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/toolbox/HttpClientTest.kt
  sample/build.gradle.kts
  sample/src/main/AndroidManifest.xml
  sample/src/main/kotlin/com/example/fuel/MainActivity.kt
  sample/src/main/kotlin/com/example/fuel/SampleApplication.kt
  settings.gradle.kts
Labels: :gem: feature

#563 [fuel-core] Add Response validator to ExecutionOption
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/RequestExecutionOptions.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/interceptors/ValidatorInterceptor.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/RequestTask.kt
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/SuspendableRequest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/InterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/RequestValidationTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/interceptors/RedirectionInterceptorTest.kt
  fuel/src/test/kotlin/com/github/kittinunf/fuel/core/interceptors/ValidatorInterceptorTest.kt
Labels: :boom: breaking change

#569 [fuel-jackson] Added custom mapper support.
  fuel-jackson/README.md
  fuel-jackson/src/main/kotlin/com/github/kittinunf/fuel/jackson/FuelJackson.kt
  fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/FuelJacksonTest.kt
Labels: :gem: feature

#581 Release version 2.0.0
  .travis.yml
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  deploy_bintray.sh
  fuel-stetho/build.gradle.kts
  fuel-stetho/src/main/java/com/github/kittinunf/fuel/stetho/StethoHook.kt
  fuel-stetho/src/test/java/com/github/kittinunf/fuel/StethoHookTest.kt
Labels: :notebook: chore

#585 [Release] version 2.0.1
  README.md
  buildSrc/src/main/kotlin/Constants.kt
  deploy_bintray.sh
  fuel-android/README.md
  fuel-coroutines/README.md
  fuel-forge/README.md
  fuel-gson/README.md
  fuel-jackson/README.md
  fuel-json/README.md
  fuel-kotlinx-serialization/README.md
  fuel-livedata/README.md
  fuel-moshi/README.md
  fuel-reactor/README.md
  fuel-rxjava/README.md
  fuel-test/README.md
  fuel/README.md
Labels: :notebook: chore
