Repository kittinunf/fuel, pull requests merged in 2019-07, with the labels that each got.

#654 Flesh out Quick Start examples
  README.md
Labels: :book: documentation

#653 Fix content length parameter for InlineDataPart
  fuel/src/main/kotlin/com/github/kittinunf/fuel/core/DataPart.kt
Labels: :bug: bug

#663 ⬆ [Release] Version 2.2.0
  buildSrc/src/main/kotlin/Constants.kt
  fuel-forge/README.md
Labels: :notebook: chore
